FROM microsoft/dotnet:latest as builder
RUN git clone https://github.com/bbepis/Hayden build && cd /build && dotnet publish -r linux-x64 -o /hayden ; exit 0

FROM ubuntu:rolling
ENTRYPOINT ["/hayden/Hayden"]
CMD ["/hayden/Hayden/config.json"]
WORKDIR /hayden
RUN apt-get update && apt-get install -y --no-install-recommends libcurl4 zlib1g libkrb5-3 liblttng-ctl0 libicu63 && apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}
COPY --from=builder /hayden /hayden
